language: python

dist: xenial

sudo: required

addons:
  apt:
    packages:
      - default-jdk

env:
  global:
    - TAGS="python"
    - GAUGE_TELEMETRY_ENABLED=false
    - GAUGE_PREFIX=/tmp
    - TERM=dumb

matrix:
  include:
    - python: 3.7
      install: "pip install -r requirements.txt"
      script:
        - python build.py --test
        - curl -sSfL https://raw.githubusercontent.com/getgauge/infrastructure/master/nightly_scripts/install_latest_gauge_nightly.sh | bash
        - export PATH=/tmp/bin:$PATH
        - gauge -v
        - python build.py --dist
        - export GAUGE_PYTHON_VERSION=$(cd bin; ls gauge-python-*.zip | sed "s/^gauge-python-\([^;]*\).zip/\1/")
        - gauge uninstall python
        - gauge install python -f "bin/gauge-python-$GAUGE_PYTHON_VERSION.zip"
        - pip install "dist/getgauge-$GAUGE_PYTHON_VERSION.tar.gz"
        - gauge config gauge_repository_url  https://raw.githubusercontent.com/getgauge/gauge-nightly-repository/master/
        - git clone git://github.com/getgauge/gauge-tests --depth 1 --recursive
        - cd gauge-tests
        - gauge install
        - gauge -v
        - ./gradlew clean pythonFT

    - os: windows
      language: sh
      python: "3.7"
      before_install:
        - choco install python3
        - choco install openjdk
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
      install:
        - pip install -r requirements.txt
      script:
        - python build.py --dist
        - PowerShell -Command 'Invoke-WebRequest -Uri "https://raw.githubusercontent.com/getgauge/infrastructure/master/nightly_scripts/install_latest_gauge_nightly.ps1" -OutFile install_latest_gauge_nightly.ps1'
        - PowerShell -File .\install_latest_gauge_nightly.ps1
        - export PATH="/c/ProgramFiles\Gauge\bin:$PATH"
        - python build.py --install
        - gauge config gauge_repository_url  https://raw.githubusercontent.com/getgauge/gauge-nightly-repository/master/
        - git clone git://github.com/getgauge/gauge-tests --depth 1 --recursive
        - cd gauge-tests
        - gauge install
        - gauge -v
        - .\gradlew.bat clean pythonFT
